# Install on CentOS 8
---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    packages:
        - git
        - make
        - chrony
        - vim

  tasks:
    - include_tasks: check-version.yml

    - name: Install required packages (this may take a while)
      dnf: 
        name: "{{ packages }}"
        state: present

    - name: configure chronyd and timezone
      service: 
        name: chronyd
        state: started 
        enabled: yes

    - name: set timezone
      timezone: name=America/Los_Angeles

    - name: TOD
      command: date
      register: tod 
    - debug: var=tod.stdout_lines

    - name: chronyc sources
      shell: sleep 5 && chronyc sources
      register: chronyc
    - debug: var=chronyc.stdout_lines
