# install on Fedora
# requires python, git, and make pre-installed
---
- hosts: all
  become: true
  tasks:

    - name: Install required Fedora packages (this may take a while)
      dnf: name={{item}} state=present
      with_items:
        - git
        - make
        - ntp

    - name: configure NTP and timezone
      service: name=ntpd state=started enabled=yes
    - name: ntpq
      command: ntpq -c peer
      register: ntpq
    - debug: var=ntpq.stdout_lines

    - name: set timezone
      timezone: name=America/Los_Angeles
    - name: TOD
      command: date
      register: tod 
    - debug: var=tod.stdout_lines

    - name: ntpq
      command: ntpq -c peer
      register: ntpq
    - debug: var=ntpq.stdout_lines
...