# Install on CentOS 6+7
# requires python, git, and make pre-installed
---
- hosts: all
  become: true
  vars:
    # ansible_python_interpreter: /usr/bin/python
    packages:
      - git
      - make
      - ntp
      - vim

  tasks:
    - include_tasks: check-version.yml

    - name: Install required packages (this may take a while)
      package: 
        name: "{{ packages }}"
        state: present
 
     # - include_tasks: ntp.yml
    - name: remove server entries
      lineinfile:
        path: /etc/ntp.conf
        regexp: "^server "
        state: absent
        backup: yes

    - name: add north-america pool server
      lineinfile:
        path: /etc/ntp.conf
        state: present
        line: "pool 0.north-america.pool.ntp.org iburst"
      notify: "restart ntp services"

    - name: enable NTP service
      service: 
        name: ntpd
        state: started 
        enabled: yes

    - name: set timezone
      timezone: name=America/Los_Angeles

    - name: TOD
      command: date
      register: tod 
    - debug: var=tod.stdout_lines

  handlers:
    # - import_tasks: ntp-handlers.yml

    - name: restart ntp
      service: name="ntpd" state=restarted
      listen: "restart ntp services"

    - name: get peers
      shell: sleep 5 && ntpq -c peer
      register: peers
      listen: "restart ntp services"

    - name: display peers after restart
      debug: var=peers.stdout_lines
      listen: "restart ntp services"
