# Install on Ubuntu
# requires python pre-installed on 16.04
---
- hosts: all
  become: true
  tasks:

    - name: Install required packages (this may take a while)
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - git
        - make
        - ntp 
        - ntpdate 
        - ntp-doc

    - name: configure NTP and timezone
      service: name=ntp state=started enabled=yes

    - name: set timezone
      timezone: name=America/Los_Angeles
    - name: TOD
      shell: sleep 4; date
      register: tod 
    - debug: var=tod.stdout_lines

    - name: ntpq
      command: ntpq -c peer
      register: ntpq
    - debug: var=ntpq.stdout_lines
