# Install on Ubuntu 18.04+
# requires python pre-installed on 18.04...needs to be installed on 20.04
---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    packages:
        - git
        - make
        - chrony
        - vim

  tasks:
    - include_tasks: check-version.yaml

    - name: Install required packages (this may take a while)
      package: 
        name: "{{ packages }}"
        state: present

    - name: set timezone
      timezone: name=America/Los_Angeles

    - name: configure chronyd
      template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
        backup: true
      register: chrony
      notify: "restart time services"
    #- debug: var=chrony


  handlers:
    - name: restart time services
      service:
          name: chronyd
          state: restarted
          enabled: yes

    - name: chrony sources
      shell: sleep 5 && chronyc sources
      register: chronyc
      listen: "restart time services"

    - debug: var="{{ item }}"
      with_items:
        - chrony.stdout_lines
        - chronyc.stdout_lines
      listen: "restart time services"
